# EV Charging Simulation - Extended Configuration
# 15+ services for comprehensive autonomous testing
# No user interaction required - fully autonomous operation

services:
  # ========== INFRASTRUCTURE ==========
  
  # Kafka Message Broker
  kafka:
    image: apache/kafka:3.7.0
    container_name: ev-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
    volumes:
      - kafka-data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions.sh --bootstrap-server localhost:9092 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s
    networks:
      - evcharging-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # ========== CENTRAL CONTROLLER ==========
  
  ev-central:
    build:
      context: .
      dockerfile: docker/Dockerfile.central
    container_name: ev-central
    ports:
      - "8000:8000"  # HTTP Dashboard
      - "9999:9999"  # TCP Control
    environment:
      CENTRAL_KAFKA_BOOTSTRAP: kafka:9092
      CENTRAL_HTTP_PORT: 8000
      CENTRAL_LISTEN_PORT: 9999
      CENTRAL_LOG_LEVEL: INFO
    depends_on:
      kafka:
        condition: service_started
    networks:
      - evcharging-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # ========== CHARGING POINT ENGINES (5 CPs) ==========
  
  ev-cp-e-1:
    build:
      context: .
      dockerfile: docker/Dockerfile.cp_e
    container_name: ev-cp-e-1
    environment:
      CP_ENGINE_KAFKA_BOOTSTRAP: kafka:9092
      CP_ENGINE_CP_ID: CP-001
      CP_ENGINE_HEALTH_PORT: 8001
      CP_ENGINE_LOG_LEVEL: INFO
      CP_ENGINE_KW_RATE: 22.0
      CP_ENGINE_EURO_RATE: 0.30
      CP_ENGINE_TELEMETRY_INTERVAL: 1.0
    depends_on:
      kafka:
        condition: service_started
    networks:
      - evcharging-network
    restart: unless-stopped

  ev-cp-e-2:
    build:
      context: .
      dockerfile: docker/Dockerfile.cp_e
    container_name: ev-cp-e-2
    environment:
      CP_ENGINE_KAFKA_BOOTSTRAP: kafka:9092
      CP_ENGINE_CP_ID: CP-002
      CP_ENGINE_HEALTH_PORT: 8002
      CP_ENGINE_LOG_LEVEL: INFO
      CP_ENGINE_KW_RATE: 50.0
      CP_ENGINE_EURO_RATE: 0.35
      CP_ENGINE_TELEMETRY_INTERVAL: 1.0
    depends_on:
      kafka:
        condition: service_started
    networks:
      - evcharging-network
    restart: unless-stopped

  ev-cp-e-3:
    build:
      context: .
      dockerfile: docker/Dockerfile.cp_e
    container_name: ev-cp-e-3
    environment:
      CP_ENGINE_KAFKA_BOOTSTRAP: kafka:9092
      CP_ENGINE_CP_ID: CP-003
      CP_ENGINE_HEALTH_PORT: 8003
      CP_ENGINE_LOG_LEVEL: INFO
      CP_ENGINE_KW_RATE: 43.0
      CP_ENGINE_EURO_RATE: 0.32
      CP_ENGINE_TELEMETRY_INTERVAL: 1.0
    depends_on:
      kafka:
        condition: service_started
    networks:
      - evcharging-network
    restart: unless-stopped

  ev-cp-e-4:
    build:
      context: .
      dockerfile: docker/Dockerfile.cp_e
    container_name: ev-cp-e-4
    environment:
      CP_ENGINE_KAFKA_BOOTSTRAP: kafka:9092
      CP_ENGINE_CP_ID: CP-004
      CP_ENGINE_HEALTH_PORT: 8004
      CP_ENGINE_LOG_LEVEL: INFO
      CP_ENGINE_KW_RATE: 150.0
      CP_ENGINE_EURO_RATE: 0.40
      CP_ENGINE_TELEMETRY_INTERVAL: 1.0
    depends_on:
      kafka:
        condition: service_started
    networks:
      - evcharging-network
    restart: unless-stopped

  ev-cp-e-5:
    build:
      context: .
      dockerfile: docker/Dockerfile.cp_e
    container_name: ev-cp-e-5
    environment:
      CP_ENGINE_KAFKA_BOOTSTRAP: kafka:9092
      CP_ENGINE_CP_ID: CP-005
      CP_ENGINE_HEALTH_PORT: 8005
      CP_ENGINE_LOG_LEVEL: INFO
      CP_ENGINE_KW_RATE: 7.2
      CP_ENGINE_EURO_RATE: 0.28
      CP_ENGINE_TELEMETRY_INTERVAL: 1.0
    depends_on:
      kafka:
        condition: service_started
    networks:
      - evcharging-network
    restart: unless-stopped

  # ========== CHARGING POINT MONITORS (5 Monitors) ==========
  
  ev-cp-m-1:
    build:
      context: .
      dockerfile: docker/Dockerfile.cp_m
    container_name: ev-cp-m-1
    environment:
      CP_MONITOR_CP_ID: CP-001
      CP_MONITOR_CP_E_HOST: ev-cp-e-1
      CP_MONITOR_CP_E_PORT: 8001
      CP_MONITOR_CENTRAL_HOST: ev-central
      CP_MONITOR_CENTRAL_PORT: 8000
      CP_MONITOR_HEALTH_INTERVAL: 2.0
      CP_MONITOR_LOG_LEVEL: INFO
    depends_on:
      - ev-central
      - ev-cp-e-1
    networks:
      - evcharging-network
    restart: unless-stopped

  ev-cp-m-2:
    build:
      context: .
      dockerfile: docker/Dockerfile.cp_m
    container_name: ev-cp-m-2
    environment:
      CP_MONITOR_CP_ID: CP-002
      CP_MONITOR_CP_E_HOST: ev-cp-e-2
      CP_MONITOR_CP_E_PORT: 8002
      CP_MONITOR_CENTRAL_HOST: ev-central
      CP_MONITOR_CENTRAL_PORT: 8000
      CP_MONITOR_HEALTH_INTERVAL: 2.0
      CP_MONITOR_LOG_LEVEL: INFO
    depends_on:
      - ev-central
      - ev-cp-e-2
    networks:
      - evcharging-network
    restart: unless-stopped

  ev-cp-m-3:
    build:
      context: .
      dockerfile: docker/Dockerfile.cp_m
    container_name: ev-cp-m-3
    environment:
      CP_MONITOR_CP_ID: CP-003
      CP_MONITOR_CP_E_HOST: ev-cp-e-3
      CP_MONITOR_CP_E_PORT: 8003
      CP_MONITOR_CENTRAL_HOST: ev-central
      CP_MONITOR_CENTRAL_PORT: 8000
      CP_MONITOR_HEALTH_INTERVAL: 2.0
      CP_MONITOR_LOG_LEVEL: INFO
    depends_on:
      - ev-central
      - ev-cp-e-3
    networks:
      - evcharging-network
    restart: unless-stopped

  ev-cp-m-4:
    build:
      context: .
      dockerfile: docker/Dockerfile.cp_m
    container_name: ev-cp-m-4
    environment:
      CP_MONITOR_CP_ID: CP-004
      CP_MONITOR_CP_E_HOST: ev-cp-e-4
      CP_MONITOR_CP_E_PORT: 8004
      CP_MONITOR_CENTRAL_HOST: ev-central
      CP_MONITOR_CENTRAL_PORT: 8000
      CP_MONITOR_HEALTH_INTERVAL: 2.0
      CP_MONITOR_LOG_LEVEL: INFO
    depends_on:
      - ev-central
      - ev-cp-e-4
    networks:
      - evcharging-network
    restart: unless-stopped

  ev-cp-m-5:
    build:
      context: .
      dockerfile: docker/Dockerfile.cp_m
    container_name: ev-cp-m-5
    environment:
      CP_MONITOR_CP_ID: CP-005
      CP_MONITOR_CP_E_HOST: ev-cp-e-5
      CP_MONITOR_CP_E_PORT: 8005
      CP_MONITOR_CENTRAL_HOST: ev-central
      CP_MONITOR_CENTRAL_PORT: 8000
      CP_MONITOR_HEALTH_INTERVAL: 2.0
      CP_MONITOR_LOG_LEVEL: INFO
    depends_on:
      - ev-central
      - ev-cp-e-5
    networks:
      - evcharging-network
    restart: unless-stopped

  # ========== DRIVER CLIENTS (3 Drivers) ==========
  
  ev-driver-alice:
    build:
      context: .
      dockerfile: docker/Dockerfile.driver
    container_name: ev-driver-alice
    environment:
      DRIVER_DRIVER_ID: driver-alice
      DRIVER_KAFKA_BOOTSTRAP: kafka:9092
      DRIVER_REQUEST_INTERVAL: 5.0
      DRIVER_LOG_LEVEL: INFO
    volumes:
      - ./requests.txt:/app/requests.txt:ro
    depends_on:
      kafka:
        condition: service_started
      ev-central:
        condition: service_started
    networks:
      - evcharging-network
    restart: unless-stopped

  ev-driver-bob:
    build:
      context: .
      dockerfile: docker/Dockerfile.driver
    container_name: ev-driver-bob
    environment:
      DRIVER_DRIVER_ID: driver-bob
      DRIVER_KAFKA_BOOTSTRAP: kafka:9092
      DRIVER_REQUEST_INTERVAL: 6.0
      DRIVER_LOG_LEVEL: INFO
    volumes:
      - ./requests.txt:/app/requests.txt:ro
    depends_on:
      kafka:
        condition: service_started
      ev-central:
        condition: service_started
    networks:
      - evcharging-network
    restart: unless-stopped

  ev-driver-charlie:
    build:
      context: .
      dockerfile: docker/Dockerfile.driver
    container_name: ev-driver-charlie
    environment:
      DRIVER_DRIVER_ID: driver-charlie
      DRIVER_KAFKA_BOOTSTRAP: kafka:9092
      DRIVER_REQUEST_INTERVAL: 7.0
      DRIVER_LOG_LEVEL: INFO
    volumes:
      - ./requests.txt:/app/requests.txt:ro
    depends_on:
      kafka:
        condition: service_started
      ev-central:
        condition: service_started
    networks:
      - evcharging-network
    restart: unless-stopped

networks:
  evcharging-network:
    driver: bridge

volumes:
  kafka-data:
